### ISSUE TITLE
API not returning user data from MongoDB

### ISSUE THREAD

**Issue by Jupiter-24** [Jupiter-24/Server#2]
There seems to be an issue with the user data retrieval from MongoDB in the Express backend.

**Comment by EfremMic** [comment]
Steps to Solve the Issue:
1. Check MongoDB Connection
First, ensure that the MongoDB connection is properly established. In the server/config/db.js, confirm that MongoDB is connected:

`const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('MongoDB connected');
  } catch (error) {
    console.error(error.message);
    process.exit(1); // Exit process with failure
  }
};

module.exports = connectDB;
` 

Ensure that:

The MongoDB connection string (MONGO_URI) in the .env file is correct.
The MongoDB server is running. And also ensure that the Mongoose schema is correctly defined for the User model. For example, in server/models/User.js:
